"""
# Circuit Visualization Module (`circuit_visualization.jl`)

Simple, focused module for generating YaoPlots circuit visualizations of VQE method ansatzes.

Key Features:
- Direct ansatz extraction from VQE method instances
- YaoPlots-based circuit diagrams saved as SVG files
- Individual plots for each VQE method
- Comprehensive analysis and comparison reports
"""

module CircuitVisualization

# ============================================================================
# Core Imports
# ============================================================================
using Printf
using Statistics
using Dates

# Import from parent BarrenPlateausVQE module
using ..Yao, ..YaoBlocks, ..YaoArrayRegister

# Optional dependencies with availability checking
global YAOPLOTS_AVAILABLE = false
global PLOTS_AVAILABLE = false
global DATAFRAMES_AVAILABLE = false
global CSV_AVAILABLE = false

try
    using YaoPlots
    global YAOPLOTS_AVAILABLE = true
    println("✅ YaoPlots.jl available for circuit visualization")
catch e
    @warn "YaoPlots.jl not available: $e"
end

try
    using Plots
    global PLOTS_AVAILABLE = true
    println("✅ Plots.jl available")
catch e
    @warn "Plots.jl not available: $e"
end

try
    using DataFrames, CSV
    global DATAFRAMES_AVAILABLE = true
    global CSV_AVAILABLE = true
    println("✅ DataFrames and CSV available for analysis")
catch e
    @warn "DataFrames/CSV not available: $e"
end

# ============================================================================
# Core Data Structures
# ============================================================================

"""
    CircuitInfo

Information about a VQE method's circuit.
"""
struct CircuitInfo
    name::String
    ansatz::Any
    n_qubits::Int
    n_parameters::Int
    method_type::String
    description::String
end

"""
    CircuitCollection

Collection of circuit information for analysis.
"""
struct CircuitCollection
    circuits::Vector{CircuitInfo}
    molecule_name::String
    n_qubits::Int
end

"""
    create_fallback_circuit_diagram(circuit_info::CircuitInfo, save_path::String)

Create a simple fallback circuit diagram when enhanced version fails.
"""
function create_fallback_circuit_diagram(circuit_info::CircuitInfo, save_path::String)
    try
        # Ensure save path has .svg extension
        svg_path = endswith(save_path, ".svg") ? save_path : replace(save_path, r"\.[^.]*$" => ".svg")
        
        # Create simple SVG fallback
        svg_content = """<?xml version="1.0" encoding="UTF-8"?>
<svg width="800" height="400" xmlns="http://www.w3.org/2000/svg">
    <style>
        .title { font-family: Arial, sans-serif; font-size: 18px; font-weight: bold; text-anchor: middle; fill: #2c3e50; }
        .subtitle { font-family: Arial, sans-serif; font-size: 14px; text-anchor: middle; fill: #34495e; }
        .info { font-family: Arial, sans-serif; font-size: 12px; text-anchor: middle; fill: #7f8c8d; }
        .warning { font-family: Arial, sans-serif; font-size: 11px; text-anchor: middle; fill: #e74c3c; }
    </style>
    <text x="400" y="30" class="title">$(circuit_info.name) Circuit</text>
    <text x="400" y="55" class="subtitle">$(circuit_info.method_type) Ansatz</text>
    <text x="400" y="80" class="info">$(circuit_info.n_qubits) qubits, $(circuit_info.n_parameters) parameters</text>
    <text x="400" y="100" class="info">$(circuit_info.description)</text>
    
    <rect x="50" y="130" width="700" height="200" fill="#f8f9fa" stroke="#dee2e6" stroke-width="2" rx="10"/>
    <text x="400" y="210" class="warning">Circuit diagram visualization unavailable</text>
    <text x="400" y="230" class="info">YaoPlots failed to generate circuit plot</text>
    <text x="400" y="250" class="info">Circuit structure exists but cannot be visualized</text>
    
    <text x="400" y="350" class="info">Generated by BarrenPlateausVQE.jl - $(Dates.now())</text>
</svg>"""
        
        open(svg_path, "w") do f
            write(f, svg_content)
        end
        
        println("  ⚠️  Created basic fallback diagram: $(basename(svg_path))")
        return true
        
    catch e
        @warn "Failed to create basic fallback diagram: $e"
        return false
    end
end
"""
    CircuitAnalysis

Analysis results for a circuit.
"""
struct CircuitAnalysis
    name::String
    method_type::String
    n_qubits::Int
    n_parameters::Int
    depth::Int
    gate_count::Dict{String, Int}
    complexity_score::Float64
end

# ============================================================================
# VQE Method Circuit Extraction
# ============================================================================

"""
    extract_circuit_from_vqe_method(method_name::String, n_qubits::Int)

Create a VQE method instance and extract its ansatz circuit.
"""
function extract_circuit_from_vqe_method(method_name::String, n_qubits::Int)
    try
        # Access VQE methods from the parent BarrenPlateausVQE module
        parent = parentmodule(@__MODULE__)
        
        if method_name == "StandardVQE"
            StandardVQE = getfield(parent, :StandardVQE)
            vqe = StandardVQE(n_qubits, 1)  # 1 layer
            return CircuitInfo(
                "StandardVQE",
                vqe.ansatz,
                vqe.n_qubits,
                vqe.n_parameters,
                "Hardware-Efficient",
                "Standard VQE with EfficientSU2 ansatz using Ry and Rz rotations"
            )
            
        elseif method_name == "SEAVQE"
            SEAVQE = getfield(parent, :SEAVQE)
            vqe = SEAVQE(n_qubits)
            return CircuitInfo(
                "SEAVQE",
                vqe.ansatz,
                vqe.n_qubits,
                vqe.n_parameters,
                "State-Efficient",
                "State Efficient Ansatz with 3-layer structure for barren plateau mitigation"
            )
            
        elseif method_name == "LocalGlobalVQE"
            LocalGlobalVQE = getfield(parent, :LocalGlobalVQE)
            vqe = LocalGlobalVQE(n_qubits, 1)  # 1 layer
            return CircuitInfo(
                "LocalGlobalVQE",
                vqe.ansatz,
                vqe.n_qubits,
                vqe.n_parameters,
                "Local-Global",
                "Local-Global VQE using same ansatz as StandardVQE but two-stage optimization"
            )
            
        elseif method_name == "AdiabaticVQE"
            AdiabaticVQE = getfield(parent, :AdiabaticVQE)
            vqe = AdiabaticVQE(n_qubits, 1)  # 1 layer
            return CircuitInfo(
                "AdiabaticVQE",
                vqe.ansatz,
                vqe.n_qubits,
                vqe.n_parameters,
                "Adiabatic",
                "Adiabatic VQE with gradual Hamiltonian interpolation"
            )
            
        elseif method_name == "PretrainedVQE"
            PretrainedVQE = getfield(parent, :PretrainedVQE)
            vqe = PretrainedVQE(n_qubits)
            # Use the full ansatz for visualization
            return CircuitInfo(
                "PretrainedVQE",
                vqe.full_ansatz,
                vqe.n_qubits,
                vqe.full_n_parameters,
                "MPS-Enhanced",
                "Pretrained VQE with MPS parameter initialization and full ansatz"
            )
            
        else
            throw(ArgumentError("Unknown VQE method: $method_name"))
        end
        
    catch e
        @warn "Failed to create $method_name: $e"
        return nothing
    end
end

"""
    extract_circuit_from_analyzer_results(method_name::String, data::Dict)

Extract circuit info from analyzer results (fallback method).
"""
function extract_circuit_from_analyzer_results(method_name::String, data::Dict)
    try
        method_result = data["method_result"]
        
        # Check if method failed
        if get(method_result, "fallback", false)
            return nothing
        end
        
        # Extract based on method structure
        ansatz = nothing
        n_qubits = 0
        n_parameters = 0
        
        if method_name == "PretrainedVQE" && haskey(method_result, "full")
            ansatz_info = method_result["full"]["ansatz_info"]
            ansatz = ansatz_info["ansatz"]
            n_qubits = ansatz_info["n_qubits"]
            n_parameters = ansatz_info["n_parameters"]
        elseif method_name == "LocalGlobalVQE" && haskey(method_result, "out")
            ansatz_info = method_result["out"]["ansatz_info"]
            ansatz = ansatz_info["ansatz"]
            n_qubits = ansatz_info["n_qubits"]
            n_parameters = ansatz_info["n_parameters"]
        elseif haskey(method_result, "ansatz_info")
            ansatz_info = method_result["ansatz_info"]
            ansatz = ansatz_info["ansatz"]
            n_qubits = ansatz_info["n_qubits"]
            n_parameters = ansatz_info["n_parameters"]
        else
            return nothing
        end
        
        if ansatz === nothing || n_qubits <= 0
            return nothing
        end
        
        # Classify method type
        method_type = if contains(lowercase(method_name), "standard")
            "Hardware-Efficient"
        elseif contains(lowercase(method_name), "sea")
            "State-Efficient"
        elseif contains(lowercase(method_name), "local")
            "Local-Global"
        elseif contains(lowercase(method_name), "adiabatic")
            "Adiabatic"
        elseif contains(lowercase(method_name), "pretrained")
            "MPS-Enhanced"
        else
            "Custom"
        end
        
        return CircuitInfo(
            method_name,
            ansatz,
            n_qubits,
            n_parameters,
            method_type,
            "Extracted from analyzer results"
        )
        
    catch e
        @warn "Failed to extract circuit from analyzer results for $method_name: $e"
        return nothing
    end
end

# ============================================================================
# Circuit Visualization Functions
# ============================================================================

"""
    create_circuit_plot(circuit_info::CircuitInfo, save_path::String)

Create a YaoPlots circuit visualization and save it.
"""
function create_circuit_plot(circuit_info::CircuitInfo, save_path::String)
    if !YAOPLOTS_AVAILABLE
        @warn "YaoPlots not available, cannot create circuit plot"
        return create_fallback_circuit_diagram(circuit_info, save_path)
    end
    
    if circuit_info.ansatz === nothing
        @warn "No ansatz available for $(circuit_info.name)"
        return create_fallback_circuit_diagram(circuit_info, save_path)
    end
    
    try
        println("🎨 Creating circuit plot for $(circuit_info.name)...")
        
        # Ensure save path has .svg extension
        svg_path = endswith(save_path, ".svg") ? save_path : replace(save_path, r"\.[^.]*$" => ".svg")
        
        # Try multiple YaoPlots approaches
        success = false
        
        # Method 1: Basic vizcircuit with minimal parameters
        try
            YaoPlots.vizcircuit(circuit_info.ansatz; format=:svg, filename=svg_path)
            if isfile(svg_path)
                success = true
            end
        catch e1
            @warn "Basic vizcircuit failed: $e1"
        end
        
        # Method 2: Try without filename parameter (save manually)
        if !success
            try
                # Create drawing without filename
                drawing = YaoPlots.vizcircuit(circuit_info.ansatz; format=:svg)
                
                # Try to save using different methods
                if hasproperty(drawing, :stream) && !isempty(drawing.stream)
                    open(svg_path, "w") do f
                        write(f, String(drawing.stream))
                    end
                    success = isfile(svg_path)
                end
            catch e2
                @warn "Manual save method failed: $e2"
            end
        end
        
        # Method 3: Try basic plot function
        if !success
            try
                drawing = YaoPlots.plot(circuit_info.ansatz)
                # This might create a display that we can't easily save
                # but let's try to extract content
                success = false  # We'll handle this in fallback
            catch e3
                @warn "Plot method failed: $e3"
            end
        end
        
        # Check if we succeeded
        if success && isfile(svg_path)
            # Add enhanced metadata to the saved SVG
            enhance_saved_svg_metadata(svg_path, circuit_info)
            println("  ✅ Saved: $(basename(svg_path))")
            return true
        else
            @warn "All YaoPlots methods failed for $(circuit_info.name), using enhanced fallback"
            return create_enhanced_circuit_diagram(circuit_info, save_path)
        end
        
    catch e
        @warn "Failed to create circuit plot for $(circuit_info.name): $e"
        # Try fallback method
        return create_enhanced_circuit_diagram(circuit_info, save_path)
    end
end

"""
    enhance_saved_svg_metadata(svg_path::String, circuit_info::CircuitInfo)

Add enhanced metadata to an already saved SVG file.
"""
function enhance_saved_svg_metadata(svg_path::String, circuit_info::CircuitInfo)
    try
        # Read the existing SVG file
        svg_content = read(svg_path, String)
        
        # Add metadata as SVG comments
        metadata_comment = """
<!-- Circuit Metadata -->
<!-- Method: $(circuit_info.name) -->
<!-- Type: $(circuit_info.method_type) -->
<!-- Qubits: $(circuit_info.n_qubits) -->
<!-- Parameters: $(circuit_info.n_parameters) -->
<!-- Description: $(circuit_info.description) -->
<!-- Generated: $(Dates.now()) -->
<!-- BarrenPlateausVQE.jl Circuit Visualization -->
"""
        
        # Insert metadata after the opening SVG tag
        enhanced_svg = replace(svg_content, 
            r"(<svg[^>]*>)" => s"\1$metadata_comment"
        )
        
        # Write back the enhanced SVG
        open(svg_path, "w") do f
            write(f, enhanced_svg)
        end
        
    catch e
        @warn "Failed to enhance SVG metadata: $e"
    end
end

"""
    create_enhanced_circuit_diagram(circuit_info::CircuitInfo, save_path::String)

Create an enhanced circuit diagram with actual circuit structure analysis.
"""
function create_enhanced_circuit_diagram(circuit_info::CircuitInfo, save_path::String)
    try
        # Ensure save path has .svg extension
        svg_path = endswith(save_path, ".svg") ? save_path : replace(save_path, r"\.[^.]*$" => ".svg")
        
        # Analyze the actual circuit structure
        gate_analysis = analyze_gate_structure(circuit_info.ansatz)
        depth = estimate_circuit_depth(circuit_info.ansatz)
        
        # Create a more detailed circuit representation
        gate_summary = if !isempty(gate_analysis)
            total_gates = sum(values(gate_analysis))
            gate_types = collect(keys(gate_analysis))
            gate_counts = collect(values(gate_analysis))
            "Gates: " * join(["$gate ($count)" for (gate, count) in zip(gate_types, gate_counts)], ", ")
        else
            "Circuit structure analysis unavailable"
        end
        
        # Create enhanced SVG with actual circuit information
        svg_content = """<?xml version="1.0" encoding="UTF-8"?>
<svg width="900" height="500" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="bgGradient" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" style="stop-color:#f8f9fa;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#e9ecef;stop-opacity:1" />
        </linearGradient>
        <pattern id="gridPattern" width="20" height="20" patternUnits="userSpaceOnUse">
            <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#dee2e6" stroke-width="0.5"/>
        </pattern>
    </defs>
    
    <style>
        .title { font-family: "Arial", sans-serif; font-size: 18px; font-weight: bold; text-anchor: middle; fill: #2c3e50; }
        .subtitle { font-family: "Arial", sans-serif; font-size: 14px; text-anchor: middle; fill: #34495e; }
        .info { font-family: "Arial", sans-serif; font-size: 12px; text-anchor: middle; fill: #7f8c8d; }
        .warning { font-family: "Arial", sans-serif; font-size: 11px; text-anchor: middle; fill: #e74c3c; }
        .structure { font-family: "Courier New", monospace; font-size: 10px; text-anchor: start; fill: #2c3e50; }
        .qubit-line { stroke: #34495e; stroke-width: 2; }
        .gate-box { fill: #3498db; stroke: #2980b9; stroke-width: 2; }
        .gate-text { font-family: "Arial", sans-serif; font-size: 10px; text-anchor: middle; fill: white; font-weight: bold; }
    </style>
    
    <!-- Background -->
    <rect width="900" height="500" fill="url(#bgGradient)"/>
    
    <!-- Header -->
    <text x="450" y="30" class="title">$(circuit_info.name) Circuit Architecture</text>
    <text x="450" y="50" class="subtitle">$(circuit_info.method_type) Ansatz</text>
    <text x="450" y="70" class="info">$(circuit_info.n_qubits) qubits • $(circuit_info.n_parameters) parameters • Depth: $depth</text>
    
    <!-- Circuit representation area -->
    <rect x="50" y="90" width="800" height="300" fill="white" stroke="#bdc3c7" stroke-width="2" rx="10"/>
    <rect x="50" y="90" width="800" height="300" fill="url(#gridPattern)" opacity="0.3"/>
    
    <!-- Qubit lines -->"""
        
        # Add qubit lines and basic gate representation
        for i in 1:circuit_info.n_qubits
            y_pos = 120 + (i-1) * (280 / max(circuit_info.n_qubits, 1))
            svg_content *= """
    <line x1="80" y1="$y_pos" x2="820" y2="$y_pos" class="qubit-line"/>
    <text x="70" y="$(y_pos + 5)" class="structure">q$i</text>"""
        end
        
        # Add symbolic gate representation
        gate_x_positions = [150, 250, 350, 450, 550, 650, 750]
        gate_index = 1
        
        for (gate_type, count) in gate_analysis
            if gate_index <= length(gate_x_positions)
                x_pos = gate_x_positions[gate_index]
                for i in 1:min(circuit_info.n_qubits, 3)  # Show on first few qubits
                    y_pos = 120 + (i-1) * (280 / max(circuit_info.n_qubits, 1))
                    svg_content *= """
    <rect x="$(x_pos-15)" y="$(y_pos-10)" width="30" height="20" class="gate-box" rx="3"/>
    <text x="$x_pos" y="$(y_pos + 3)" class="gate-text">$gate_type</text>"""
                end
                gate_index += 1
            end
        end
        
        svg_content *= """
    
    <!-- Warning message -->
    <text x="450" y="420" class="warning">⚠ YaoPlots visualization failed - showing circuit structure analysis</text>
    
    <!-- Structure analysis -->
    <text x="450" y="440" class="info">$gate_summary</text>
    <text x="450" y="455" class="info">$(circuit_info.description)</text>
    
    <!-- Footer -->
    <text x="450" y="485" class="info">Generated by BarrenPlateausVQE.jl - $(Dates.now())</text>
</svg>"""
        
        open(svg_path, "w") do f
            write(f, svg_content)
        end
        
        println("  ✅ Created enhanced diagram: $(basename(svg_path))")
        return true
        
    catch e
        @warn "Failed to create enhanced diagram: $e"
        return create_fallback_circuit_diagram(circuit_info, save_path)
    end
end

"""
    add_circuit_metadata_to_svg(svg_content::String, circuit_info::CircuitInfo)

Add title and metadata to SVG content.
"""
function add_circuit_metadata_to_svg(svg_content::String, circuit_info::CircuitInfo)
    try
        # Create title and subtitle
        title = "$(replace(circuit_info.name, "_" => " ")) Ansatz Circuit"
        subtitle = "$(circuit_info.n_qubits) qubits • $(circuit_info.n_parameters) parameters • $(circuit_info.method_type)"
        
        # Find SVG dimensions
        width_match = match(r"width=\"([^\"]*)\""i, svg_content)
        height_match = match(r"height=\"([^\"]*)\""i, svg_content)
        
        if width_match !== nothing && height_match !== nothing
            width = try
                parse(Float64, width_match.captures[1])
            catch
                400.0
            end
            height = try
                parse(Float64, height_match.captures[1])
            catch
                300.0
            end
            
            # Create title elements
            title_elements = """
            <!-- Circuit Title and Metadata -->
            <style>
                .circuit-title { 
                    font-family: "Arial", sans-serif; 
                    font-size: 14px; 
                    font-weight: bold; 
                    text-anchor: middle; 
                    fill: #2c3e50;
                }
                .circuit-subtitle { 
                    font-family: "Arial", sans-serif; 
                    font-size: 11px; 
                    text-anchor: middle; 
                    fill: #7f8c8d;
                }
                .circuit-description {
                    font-family: "Arial", sans-serif; 
                    font-size: 9px; 
                    text-anchor: middle; 
                    fill: #95a5a6;
                }
            </style>
            <text x="$(width/2)" y="20" class="circuit-title">$title</text>
            <text x="$(width/2)" y="35" class="circuit-subtitle">$subtitle</text>
            <text x="$(width/2)" y="48" class="circuit-description">$(circuit_info.description)</text>
            <g transform="translate(0, 60)">
            """
            
            # Insert title after opening SVG tag and wrap content
            svg_with_title = replace(svg_content, 
                r"(<svg[^>]*>)" => s"\1$title_elements"
            )
            
            # Close the transform group before closing SVG
            svg_with_title = replace(svg_with_title, 
                "</svg>" => "</g></svg>"
            )
            
            # Update height to accommodate title
            svg_with_title = replace(svg_with_title, 
                r"height=\"([^\"]*)\""i => "height=\"$(height + 70)\""
            )
            
            return svg_with_title
        else
            # Fallback: just add a comment
            comment = "<!-- $title: $subtitle -->"
            return replace(svg_content, r"(<svg[^>]*>)" => s"\1$comment")
        end
        
    catch e
        @warn "Failed to add title to SVG: $e"
        return svg_content
    end
end

# ============================================================================
# Main Visualization Functions
# ============================================================================

"""
    visualize_all_ansatz_circuits(analyzer; output_dir::String="./ansatz_circuits", file_format::String="pdf")

Generate circuit visualizations for all VQE methods.
"""
function visualize_all_ansatz_circuits(analyzer; 
                                      output_dir::String="./ansatz_circuits", 
                                      file_format::String="pdf")
    
    # Create output directory
    mkpath(output_dir)
    
    println("🎨 Creating VQE ansatz circuit visualizations...")
    println("   📁 Output directory: $output_dir")
    println("   📄 Format: $file_format")
    
    # Get system info
    n_qubits = analyzer.molecular_system.n_qubits
    molecule_name = analyzer.molecular_system.name
    
    # VQE methods to visualize
    vqe_methods = ["StandardVQE", "SEAVQE", "LocalGlobalVQE", "AdiabaticVQE", "PretrainedVQE"]
    
    circuit_infos = CircuitInfo[]
    saved_files = String[]
    
    println("   🔍 Processing $(length(vqe_methods)) VQE methods for $molecule_name ($(n_qubits) qubits)")
    
    for method_name in vqe_methods
        println("   🔧 Processing $method_name...")
        
        # Try to extract circuit from VQE method directly
        circuit_info = extract_circuit_from_vqe_method(method_name, n_qubits)
        
        # Fallback: try to extract from analyzer results if available
        if circuit_info === nothing && haskey(analyzer.results, method_name)
            circuit_info = extract_circuit_from_analyzer_results(method_name, analyzer.results[method_name])
        end
        
        if circuit_info !== nothing
            push!(circuit_infos, circuit_info)
            
            # Create circuit visualization
            circuit_filename = "ansatz_$(method_name).svg"
            circuit_path = joinpath(output_dir, circuit_filename)
            
            if create_circuit_plot(circuit_info, circuit_path)
                push!(saved_files, circuit_path)
                
                # Display circuit statistics
                println("     📊 $(circuit_info.n_parameters) parameters, $(circuit_info.method_type) type")
            else
                @warn "Failed to create plot for $method_name"
            end
            
            # Create detailed text analysis
            info_filename = "$(method_name)_analysis.txt"
            info_path = joinpath(output_dir, info_filename)
            create_circuit_analysis_file(circuit_info, info_path)
            push!(saved_files, info_path)
            
        else
            @warn "Could not extract circuit for $method_name"
        end
    end
    
    # Create summary and comparison files
    if !isempty(circuit_infos)
        summary_files = create_analysis_summary(circuit_infos, molecule_name, output_dir)
        append!(saved_files, summary_files)
    end
    
    # Print final summary
    println("\n📊 Circuit Visualization Summary:")
    println("   ✅ Successfully processed: $(length(circuit_infos))/$(length(vqe_methods)) methods")
    println("   📁 Total files created: $(length(saved_files))")
    
    if !isempty(saved_files)
        println("\n📄 Generated Files:")
        for file in saved_files
            println("     • $(basename(file))")
        end
    end
    
    return saved_files
end

# ============================================================================
# Analysis and Summary Functions
# ============================================================================

"""
    analyze_circuit_architectures(analyzer)

Analyze circuit architectures and return a CircuitCollection.
"""
function analyze_circuit_architectures(analyzer)
    circuits = CircuitAnalysis[]
    
    # Get system info
    n_qubits = analyzer.molecular_system.n_qubits
    molecule_name = analyzer.molecular_system.name
    
    # VQE methods to analyze
    vqe_methods = ["StandardVQE", "SEAVQE", "LocalGlobalVQE", "AdiabaticVQE", "PretrainedVQE"]
    
    for method_name in vqe_methods
        try
            # Extract circuit info
            circuit_info = extract_circuit_from_vqe_method(method_name, n_qubits)
            
            if circuit_info !== nothing
                # Analyze circuit structure
                depth = estimate_circuit_depth(circuit_info.ansatz)
                gate_count = analyze_gate_structure(circuit_info.ansatz)
                complexity = calculate_complexity_score(circuit_info, depth, gate_count)
                
                analysis = CircuitAnalysis(
                    circuit_info.name,
                    circuit_info.method_type,
                    circuit_info.n_qubits,
                    circuit_info.n_parameters,
                    depth,
                    gate_count,
                    complexity
                )
                
                push!(circuits, analysis)
            else
                # Create failed entry
                failed_analysis = CircuitAnalysis(
                    method_name,
                    "Failed",
                    n_qubits,
                    0,
                    0,
                    Dict{String, Int}(),
                    0.0
                )
                push!(circuits, failed_analysis)
            end
            
        catch e
            @warn "Failed to analyze $method_name: $e"
            # Create failed entry
            failed_analysis = CircuitAnalysis(
                method_name,
                "Failed",
                n_qubits,
                0,
                0,
                Dict{String, Int}(),
                0.0
            )
            push!(circuits, failed_analysis)
        end
    end
    
    return CircuitCollection(circuits, molecule_name, n_qubits)
end

"""
    calculate_complexity_score(circuit_info::CircuitInfo, depth::Int, gate_count::Dict{String, Int})

Calculate a complexity score for the circuit.
"""
function calculate_complexity_score(circuit_info::CircuitInfo, depth::Int, gate_count::Dict{String, Int})
    try
        total_gates = sum(values(gate_count))
        gate_diversity = length(gate_count)
        param_density = circuit_info.n_parameters / circuit_info.n_qubits
        
        # Weighted complexity score
        complexity = 0.3 * param_density + 0.3 * (total_gates / circuit_info.n_qubits) + 
                    0.2 * (depth / circuit_info.n_qubits) + 0.2 * (gate_diversity / 10)
        
        return complexity
    catch
        return 0.0
    end
end

"""
    create_ansatz_comparison_grid(circuit_collection::CircuitCollection; save_path::String="")

Create a comparison grid of all ansatz circuits.
"""
function create_ansatz_comparison_grid(circuit_collection::CircuitCollection; save_path::String="")
    # This is a placeholder - would need sophisticated layout for actual grid
    # For now, just return a success indicator
    try
        if !isempty(save_path)
            # Create a simple comparison summary as SVG
            create_comparison_summary_svg(circuit_collection, save_path)
            return save_path
        end
    catch e
        @warn "Failed to create comparison grid: $e"
    end
    return nothing
end

"""
    create_comparison_summary_svg(circuit_collection::CircuitCollection, save_path::String)

Create a simple comparison summary as SVG.
"""
function create_comparison_summary_svg(circuit_collection::CircuitCollection, save_path::String)
    valid_circuits = filter(c -> c.method_type != "Failed", circuit_collection.circuits)
    
    svg_content = """<?xml version="1.0" encoding="UTF-8"?>
<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg">
    <style>
        .title { font-family: Arial, sans-serif; font-size: 20px; font-weight: bold; text-anchor: middle; fill: #2c3e50; }
        .subtitle { font-family: Arial, sans-serif; font-size: 14px; text-anchor: middle; fill: #34495e; }
        .method { font-family: Arial, sans-serif; font-size: 12px; text-anchor: start; fill: #2c3e50; }
        .value { font-family: Arial, sans-serif; font-size: 11px; text-anchor: start; fill: #7f8c8d; }
        .footer { font-family: Arial, sans-serif; font-size: 10px; text-anchor: middle; fill: #95a5a6; }
    </style>
    <text x="400" y="30" class="title">VQE Methods Comparison - $(circuit_collection.molecule_name)</text>
    <text x="400" y="55" class="subtitle">$(circuit_collection.n_qubits) Qubits System</text>
    
    <text x="50" y="100" class="method">Method</text>
    <text x="200" y="100" class="method">Type</text>
    <text x="350" y="100" class="method">Parameters</text>
    <text x="450" y="100" class="method">Depth</text>
    <text x="550" y="100" class="method">Complexity</text>
    
    <line x1="40" y1="110" x2="760" y2="110" stroke="#bdc3c7" stroke-width="1"/>
"""
    
    y_pos = 130
    for circuit in valid_circuits
        svg_content *= """
    <text x="50" y="$y_pos" class="value">$(circuit.name)</text>
    <text x="200" y="$y_pos" class="value">$(circuit.method_type)</text>
    <text x="350" y="$y_pos" class="value">$(circuit.n_parameters)</text>
    <text x="450" y="$y_pos" class="value">$(circuit.depth)</text>
    <text x="550" y="$y_pos" class="value">$(round(circuit.complexity_score, digits=2))</text>
        """
        y_pos += 25
    end
    
    svg_content *= """
    <text x="400" y="$(y_pos + 50)" class="footer">Generated by BarrenPlateausVQE.jl - $(Dates.now())</text>
</svg>"""
    
    open(save_path, "w") do f
        write(f, svg_content)
    end
end

"""
    create_circuit_analysis_file(circuit_info::CircuitInfo, file_path::String)

Create detailed text analysis file for a circuit.
"""
function create_circuit_analysis_file(circuit_info::CircuitInfo, file_path::String)
    try
        open(file_path, "w") do f
            # Fix string multiplication syntax using repeat()
            separator = repeat("=", 60)
            write(f, separator, "\n")
            write(f, "$(circuit_info.name) CIRCUIT ANALYSIS\n")
            write(f, separator, "\n\n")
            
            write(f, "Method Information:\n")
            write(f, repeat("-", 18), "\n")
            write(f, "Name: $(circuit_info.name)\n")
            write(f, "Type: $(circuit_info.method_type)\n")
            write(f, "Description: $(circuit_info.description)\n\n")
            
            write(f, "Circuit Specifications:\n")
            write(f, repeat("-", 21), "\n")
            write(f, "Qubits: $(circuit_info.n_qubits)\n")
            write(f, "Parameters: $(circuit_info.n_parameters)\n")
            write(f, "Parameter Density: $(round(circuit_info.n_parameters / circuit_info.n_qubits, digits=2)) params/qubit\n\n")
            
            # Add circuit structure analysis
            if circuit_info.ansatz !== nothing
                try
                    depth = estimate_circuit_depth(circuit_info.ansatz)
                    write(f, "Circuit Depth: $depth\n")
                    
                    gate_analysis = analyze_gate_structure(circuit_info.ansatz)
                    if !isempty(gate_analysis)
                        write(f, "\nGate Analysis:\n")
                        write(f, repeat("-", 13), "\n")
                        for (gate_type, count) in gate_analysis
                            write(f, "$gate_type: $count\n")
                        end
                        total_gates = sum(values(gate_analysis))
                        write(f, "Total Gates: $total_gates\n")
                        write(f, "Gate Density: $(round(total_gates / circuit_info.n_qubits, digits=2)) gates/qubit\n")
                    end
                catch e
                    write(f, "Circuit structure analysis failed: $e\n")
                end
            end
            
            write(f, "\n")
            write(f, separator, "\n")
            write(f, "Generated: $(Dates.now())\n")
            write(f, "BarrenPlateausVQE.jl Circuit Visualization\n")
        end
        
    catch e
        @warn "Failed to create analysis file: $e"
    end
end

"""
    estimate_circuit_depth(ansatz)

Estimate the depth of a quantum circuit.
"""
function estimate_circuit_depth(ansatz)
    try
        if hasproperty(ansatz, :blocks) && isa(getproperty(ansatz, :blocks), Vector)
            return length(getproperty(ansatz, :blocks))
        else
            return 1
        end
    catch
        return 1
    end
end

"""
    analyze_gate_structure(ansatz)

Analyze the gate structure of a quantum circuit.
"""
function analyze_gate_structure(ansatz)
    gate_count = Dict{String, Int}()
    try
        count_gates_recursive!(ansatz, gate_count)
    catch e
        @warn "Gate analysis failed: $e"
    end
    return gate_count
end

"""
    count_gates_recursive!(block, gate_count::Dict{String, Int})

Recursively count gates in a circuit.
"""
function count_gates_recursive!(block, gate_count::Dict{String, Int})
    if block === nothing
        return
    end
    
    try
        block_type = typeof(block)
        type_name = string(block_type)
        
        if contains(type_name, "Chain") && hasproperty(block, :blocks)
            for sub_block in getproperty(block, :blocks)
                count_gates_recursive!(sub_block, gate_count)
            end
        elseif contains(type_name, "Put")
            if hasproperty(block, :content)
                content = getproperty(block, :content)
                gate_name = identify_gate_type(content)
                gate_count[gate_name] = get(gate_count, gate_name, 0) + 1
            else
                gate_count["Put"] = get(gate_count, "Put", 0) + 1
            end
        elseif contains(type_name, "Control")
            gate_count["CNOT"] = get(gate_count, "CNOT", 0) + 1
        else
            simplified_name = replace(type_name, r".*\." => "")
            gate_count[simplified_name] = get(gate_count, simplified_name, 0) + 1
        end
    catch e
        @warn "Gate counting failed: $e"
    end
end

"""
    identify_gate_type(gate)

Identify the type of a quantum gate.
"""
function identify_gate_type(gate)
    try
        gate_type = typeof(gate)
        type_name = string(gate_type)
        
        if contains(type_name, "Ry")
            return "Ry"
        elseif contains(type_name, "Rz")
            return "Rz"
        elseif contains(type_name, "Rx")
            return "Rx"
        elseif contains(type_name, "X")
            return "X"
        elseif contains(type_name, "Y")
            return "Y"
        elseif contains(type_name, "Z")
            return "Z"
        elseif contains(type_name, "H")
            return "H"
        else
            return replace(type_name, r".*\." => "")
        end
    catch
        return "Unknown"
    end
end

"""
    create_analysis_summary(circuit_infos::Vector{CircuitInfo}, molecule_name::String, output_dir::String)

Create summary files comparing all methods.
"""
function create_analysis_summary(circuit_infos::Vector{CircuitInfo}, molecule_name::String, output_dir::String)
    summary_files = String[]
    
    # Create markdown summary
    md_path = joinpath(output_dir, "VQE_Methods_Summary.md")
    create_markdown_summary(circuit_infos, molecule_name, md_path)
    push!(summary_files, md_path)
    
    # Create CSV data if available
    if DATAFRAMES_AVAILABLE && CSV_AVAILABLE
        csv_path = joinpath(output_dir, "VQE_Methods_Data.csv")
        create_csv_summary(circuit_infos, csv_path)
        push!(summary_files, csv_path)
    end
    
    return summary_files
end

"""
    create_markdown_summary(circuit_infos::Vector{CircuitInfo}, molecule_name::String, file_path::String)

Create a comprehensive markdown summary.
"""
function create_markdown_summary(circuit_infos::Vector{CircuitInfo}, molecule_name::String, file_path::String)
    try
        open(file_path, "w") do f
            write(f, "# VQE Ansatz Circuit Analysis: $molecule_name\n\n")
            write(f, "**Generated**: $(Dates.now())\n")
            write(f, "**System**: $molecule_name\n")
            write(f, "**Methods Analyzed**: $(length(circuit_infos))\n\n")
            
            # Summary table
            write(f, "## Methods Overview\n\n")
            write(f, "| Method | Type | Qubits | Parameters | Param/Qubit | Circuit File |\n")
            write(f, "|--------|------|--------|------------|-------------|-------------|\n")
            
            for info in circuit_infos
                param_density = round(info.n_parameters / info.n_qubits, digits=2)
                write(f, "| $(info.name) | $(info.method_type) | $(info.n_qubits) | $(info.n_parameters) | $param_density | ansatz_$(info.name).svg |\n")
            end
            
            # Detailed analysis
            write(f, "\n## Detailed Analysis\n\n")
            for info in circuit_infos
                write(f, "### $(info.name)\n\n")
                write(f, "- **Type**: $(info.method_type)\n")
                write(f, "- **Description**: $(info.description)\n")
                write(f, "- **Parameters**: $(info.n_parameters)\n")
                write(f, "- **Parameter Density**: $(round(info.n_parameters / info.n_qubits, digits=2)) params/qubit\n")
                write(f, "- **Circuit File**: [ansatz_$(info.name).svg](ansatz_$(info.name).svg)\n")
                write(f, "- **Analysis File**: [$(info.name)_analysis.txt]($(info.name)_analysis.txt)\n\n")
            end
            
            # Statistics
            write(f, "## Statistics\n\n")
            params = [info.n_parameters for info in circuit_infos]
            write(f, "- **Average Parameters**: $(round(mean(params), digits=2))\n")
            write(f, "- **Parameter Range**: $(minimum(params)) - $(maximum(params))\n")
            
            if length(params) > 1
                most_efficient_idx = argmin(params)
                most_complex_idx = argmax(params)
                write(f, "- **Most Efficient**: $(circuit_infos[most_efficient_idx].name) ($(params[most_efficient_idx]) parameters)\n")
                write(f, "- **Most Complex**: $(circuit_infos[most_complex_idx].name) ($(params[most_complex_idx]) parameters)\n")
            end
            
            write(f, "\n---\n*Generated by BarrenPlateausVQE.jl Circuit Visualization*\n")
        end
        
    catch e
        @warn "Failed to create markdown summary: $e"
    end
end

"""
    create_csv_summary(circuit_infos::Vector{CircuitInfo}, file_path::String)

Create CSV data file for further analysis.
"""
function create_csv_summary(circuit_infos::Vector{CircuitInfo}, file_path::String)
    try
        df = DataFrames.DataFrame(
            Method = [info.name for info in circuit_infos],
            Type = [info.method_type for info in circuit_infos],
            Qubits = [info.n_qubits for info in circuit_infos],
            Parameters = [info.n_parameters for info in circuit_infos],
            Param_per_Qubit = [round(info.n_parameters / info.n_qubits, digits=2) for info in circuit_infos],
            Description = [info.description for info in circuit_infos]
        )
        
        CSV.write(file_path, df)
        
    catch e
        @warn "Failed to create CSV summary: $e"
    end
end

# ============================================================================
# Module Exports
# ============================================================================

export CircuitInfo, CircuitCollection, CircuitAnalysis
export extract_circuit_from_vqe_method, visualize_all_ansatz_circuits
export create_circuit_plot, create_analysis_summary, analyze_circuit_architectures, create_ansatz_comparison_grid

# ============================================================================
# Module Initialization
# ============================================================================

function __init__()
    println("\n🎨 CircuitVisualization.jl Module Loaded")
    println("   Focused VQE circuit visualization for BarrenPlateausVQE.jl")
    
    if YAOPLOTS_AVAILABLE
        println("   ✅ YaoPlots available - ready for circuit visualization!")
    else
        println("   ⚠️  YaoPlots not available - limited functionality")
    end
end

end # module CircuitVisualization